# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto_buf_schemas.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto_buf_schemas.proto',
  package='',
  serialized_pb=_b('\n\x17proto_buf_schemas.proto\"\xa9\x02\n\x0b\x64\x65scription\x12\x12\n\nclientName\x18\x01 \x02(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\"\n\x06points\x18\x03 \x03(\x0b\x32\x12.description.point\x12$\n\x07\x61\x63tions\x18\x04 \x03(\x0b\x32\x13.description.action\x1a/\n\x05point\x12\x11\n\tpointName\x18\x01 \x02(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x1av\n\x06\x61\x63tion\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12/\n\targuments\x18\x03 \x03(\x0b\x32\x1c.description.action.argument\x1a\x18\n\x08\x61rgument\x12\x0c\n\x04name\x18\x01 \x02(\t\"\xc5\x01\n\x0b\x61\x63tionQuery\x12\x10\n\x08remitent\x18\x01 \x02(\t\x12\x12\n\nactionName\x18\x02 \x02(\t\x12\n\n\x02id\x18\x03 \x02(\x04\x12\x0b\n\x03qos\x18\x04 \x02(\t\x12(\n\targuments\x18\x05 \x03(\x0b\x32\x15.actionQuery.argument\x1aM\n\x08\x61rgument\x12\x0e\n\x06strVal\x18\x01 \x01(\t\x12\x10\n\x08\x66loatVal\x18\x02 \x01(\x02\x12\x0e\n\x06intVal\x18\x03 \x01(\x03\x12\x0f\n\x07\x62oolVal\x18\x04 \x01(\x08\"\x8d\x01\n\x0e\x61\x63tionResponse\x12\n\n\x02id\x18\x01 \x02(\x04\x12\x13\n\x0bintResponse\x18\x02 \x01(\x03\x12\x15\n\rfloatResponse\x18\x03 \x01(\x02\x12\x14\n\x0c\x62oolResponse\x18\x04 \x01(\x08\x12\x13\n\x0bstrResponse\x18\x05 \x01(\t\x12\x18\n\x10\x65rrorDescription\x18\x06 \x01(\t\"d\n\x0bpointUpdate\x12\x13\n\x0bintResponse\x18\x01 \x01(\x03\x12\x15\n\rfloatResponse\x18\x02 \x01(\x02\x12\x14\n\x0c\x62oolResponse\x18\x03 \x01(\x08\x12\x13\n\x0bstrResponse\x18\x04 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DESCRIPTION_POINT = _descriptor.Descriptor(
  name='point',
  full_name='description.point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pointName', full_name='description.point.pointName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='description.point.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=205,
)

_DESCRIPTION_ACTION_ARGUMENT = _descriptor.Descriptor(
  name='argument',
  full_name='description.action.argument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='description.action.argument.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=325,
)

_DESCRIPTION_ACTION = _descriptor.Descriptor(
  name='action',
  full_name='description.action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='description.action.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='description.action.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='arguments', full_name='description.action.arguments', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DESCRIPTION_ACTION_ARGUMENT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=325,
)

_DESCRIPTION = _descriptor.Descriptor(
  name='description',
  full_name='description',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientName', full_name='description.clientName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='description.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='points', full_name='description.points', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='actions', full_name='description.actions', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DESCRIPTION_POINT, _DESCRIPTION_ACTION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=325,
)


_ACTIONQUERY_ARGUMENT = _descriptor.Descriptor(
  name='argument',
  full_name='actionQuery.argument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='strVal', full_name='actionQuery.argument.strVal', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='floatVal', full_name='actionQuery.argument.floatVal', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='intVal', full_name='actionQuery.argument.intVal', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='boolVal', full_name='actionQuery.argument.boolVal', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=448,
  serialized_end=525,
)

_ACTIONQUERY = _descriptor.Descriptor(
  name='actionQuery',
  full_name='actionQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='remitent', full_name='actionQuery.remitent', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='actionName', full_name='actionQuery.actionName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='actionQuery.id', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='qos', full_name='actionQuery.qos', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='arguments', full_name='actionQuery.arguments', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ACTIONQUERY_ARGUMENT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=525,
)


_ACTIONRESPONSE = _descriptor.Descriptor(
  name='actionResponse',
  full_name='actionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='actionResponse.id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='intResponse', full_name='actionResponse.intResponse', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='floatResponse', full_name='actionResponse.floatResponse', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='boolResponse', full_name='actionResponse.boolResponse', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strResponse', full_name='actionResponse.strResponse', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errorDescription', full_name='actionResponse.errorDescription', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=528,
  serialized_end=669,
)


_POINTUPDATE = _descriptor.Descriptor(
  name='pointUpdate',
  full_name='pointUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='intResponse', full_name='pointUpdate.intResponse', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='floatResponse', full_name='pointUpdate.floatResponse', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='boolResponse', full_name='pointUpdate.boolResponse', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strResponse', full_name='pointUpdate.strResponse', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=671,
  serialized_end=771,
)

_DESCRIPTION_POINT.containing_type = _DESCRIPTION
_DESCRIPTION_ACTION_ARGUMENT.containing_type = _DESCRIPTION_ACTION
_DESCRIPTION_ACTION.fields_by_name['arguments'].message_type = _DESCRIPTION_ACTION_ARGUMENT
_DESCRIPTION_ACTION.containing_type = _DESCRIPTION
_DESCRIPTION.fields_by_name['points'].message_type = _DESCRIPTION_POINT
_DESCRIPTION.fields_by_name['actions'].message_type = _DESCRIPTION_ACTION
_ACTIONQUERY_ARGUMENT.containing_type = _ACTIONQUERY
_ACTIONQUERY.fields_by_name['arguments'].message_type = _ACTIONQUERY_ARGUMENT
DESCRIPTOR.message_types_by_name['description'] = _DESCRIPTION
DESCRIPTOR.message_types_by_name['actionQuery'] = _ACTIONQUERY
DESCRIPTOR.message_types_by_name['actionResponse'] = _ACTIONRESPONSE
DESCRIPTOR.message_types_by_name['pointUpdate'] = _POINTUPDATE

description = _reflection.GeneratedProtocolMessageType('description', (_message.Message,), dict(

  point = _reflection.GeneratedProtocolMessageType('point', (_message.Message,), dict(
    DESCRIPTOR = _DESCRIPTION_POINT,
    __module__ = 'proto_buf_schemas_pb2'
    # @@protoc_insertion_point(class_scope:description.point)
    ))
  ,

  action = _reflection.GeneratedProtocolMessageType('action', (_message.Message,), dict(

    argument = _reflection.GeneratedProtocolMessageType('argument', (_message.Message,), dict(
      DESCRIPTOR = _DESCRIPTION_ACTION_ARGUMENT,
      __module__ = 'proto_buf_schemas_pb2'
      # @@protoc_insertion_point(class_scope:description.action.argument)
      ))
    ,
    DESCRIPTOR = _DESCRIPTION_ACTION,
    __module__ = 'proto_buf_schemas_pb2'
    # @@protoc_insertion_point(class_scope:description.action)
    ))
  ,
  DESCRIPTOR = _DESCRIPTION,
  __module__ = 'proto_buf_schemas_pb2'
  # @@protoc_insertion_point(class_scope:description)
  ))
_sym_db.RegisterMessage(description)
_sym_db.RegisterMessage(description.point)
_sym_db.RegisterMessage(description.action)
_sym_db.RegisterMessage(description.action.argument)

actionQuery = _reflection.GeneratedProtocolMessageType('actionQuery', (_message.Message,), dict(

  argument = _reflection.GeneratedProtocolMessageType('argument', (_message.Message,), dict(
    DESCRIPTOR = _ACTIONQUERY_ARGUMENT,
    __module__ = 'proto_buf_schemas_pb2'
    # @@protoc_insertion_point(class_scope:actionQuery.argument)
    ))
  ,
  DESCRIPTOR = _ACTIONQUERY,
  __module__ = 'proto_buf_schemas_pb2'
  # @@protoc_insertion_point(class_scope:actionQuery)
  ))
_sym_db.RegisterMessage(actionQuery)
_sym_db.RegisterMessage(actionQuery.argument)

actionResponse = _reflection.GeneratedProtocolMessageType('actionResponse', (_message.Message,), dict(
  DESCRIPTOR = _ACTIONRESPONSE,
  __module__ = 'proto_buf_schemas_pb2'
  # @@protoc_insertion_point(class_scope:actionResponse)
  ))
_sym_db.RegisterMessage(actionResponse)

pointUpdate = _reflection.GeneratedProtocolMessageType('pointUpdate', (_message.Message,), dict(
  DESCRIPTOR = _POINTUPDATE,
  __module__ = 'proto_buf_schemas_pb2'
  # @@protoc_insertion_point(class_scope:pointUpdate)
  ))
_sym_db.RegisterMessage(pointUpdate)


# @@protoc_insertion_point(module_scope)
